version: '3.1'

services:
  pardjs-users-service:
    container_name: pardjs-users-service
    image: registry.cn-shanghai.aliyuncs.com/pardjs/users-service:1.0.6
    restart: always
    environment: 
      NODE_ENV: production
      DB_URL: postgres://pardjs:example@pardjs-cms-service-db:5432/pardjs-cms-service
      SUPER_ADMIN_INITIAL_PASSWORD: password
      JWT_SECRET: jwt-secret
      LOGIN_SESSION_LIFE_HOURS: 100
      PASSWORD_HASH_KEY: password-hash
      IP_WHITE_LIST: 127.0.0.1
      IP_WHITE_LIST_USERNAME: white_list_user
    ports:
      - 5005:5000
    networks: 
      - pardjs-cms-service
networks: 
  pardjs-cms-service: